import NProgress from "@/components/provider/NProgress";
import Navbar from "@/components/shared/navbar";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NProgress />
      <body className={manrope.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
